version: '3'
# https://github.com/nanoninja/docker-nginx-php-mysql/blob/master/docker-compose.yml
networks:
  dujiaoka:

services:

  nginx:
    container_name: djk01_nginx
    image: nginx:1.18
    restart: unless-stopped
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/sites-enabled:/etc/nginx/conf.d/
      - ./workdir:/workdir
    networks:
      - dujiaoka
    ports:
      - "8082:80"
    depends_on:
      - php
      - epusdt

  php:
    container_name: djk01_php
    # images: jeruen/dujiaofakaphp:1.0.0
    build: ./build/php
    restart: unless-stopped
    volumes:
      - ./conf/supervisor/conf.d:/etc/supervisor/conf.d/
      - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./workdir/logs/php:/opt/log/php
      - ./workdir:/workdir
    networks:
      - dujiaoka
    depends_on:
      - mysql
      - redis_dujiaoka
    environment:
      - TZ=Asia/Shanghai

  mysql:
    container_name: djk01_mysql
    build: ./build/mysql
    # image: mysql:5.7
    restart: unless-stopped
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - ./workdir/mysql/data/:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=MYSQL_PASSWORD_REPLACE
    networks:
      - dujiaoka
    ports:
      - "33062:3306"

  redis_dujiaoka:
    container_name: djk01_redis_dujiaoka
    image: redis:6.0.9
    restart: unless-stopped
    networks:
      - dujiaoka

  redis_epusdt:
    container_name: djk01_redis_epusdt
    image: redis:6.0.9
    restart: unless-stopped
    networks:
      - dujiaoka

  epusdt:
    container_name: djk01_epusdt
    image: stilleshan/epusdt
    restart: unless-stopped
    volumes:
      - ./conf/epusdt/.env:/app/.env:ro
    networks:
      - dujiaoka
    depends_on:
      - mysql
      - redis_epusdt
